mini_projekt/mini_projekt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^admin/', include(admin.site.urls)),
  url(r'^', include('use_cases.urls', namespace="use_cases")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_projekt/use_cases/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.Home.as_view(), name="index"),
    url(r'^upload_image/$', views.Upload_image.as_view(), name='upload_image'),
    url(r'^search_image/$', views.Search_image.as_view(), name='search_image'),
    url(r'^show_image/$', views.Show_image.as_view(), name='show_image'),
    url(r'^delete/$', views.deleteImage, name='delete_image'),
]

mini_projekt/use_cases/models.py
from django.db import models

# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver


class Image(models.Model):
    image_id = models.CharField(max_length=100, null=True)
    pic = models.FileField("Image", upload_to="uploads/images/")
    DI = models.FileField("DiskImage", upload_to="uploads/diskimages/", null=True)
    upload_date = models.DateTimeField(auto_now_add=True)


@receiver(pre_delete, sender=Image)
def image_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.pic.delete(False)
    instance.DI.delete(False)

mini_projekt/use_cases/forms.py
from django import forms


class UploadImageForm(forms.Form):
    DI_TYPE = (("VMI", "Virtual machine Image"),
               ("CI", "Container Image"))
    DI_FORMAT = (("ISO", "ISO"),
                 ("DMG", "DMG"),
                 ("FVD", "FVD"),
                 ("IMG", "IMG"),
                 ("NDIF", "NDIF"),
                 ("QCOW", "QCOW"),
                 ("UDIF", "UDIF"),
                 ("VID", "VDI"),
                 ("VHD", "VHD"),
                 ("VMDK", "VMDK"),
                 ("WIM", "WIM"))
    DI_OS = (("10", "Windows"),
             ("20", "Linux"),
             ("30", "Macintosh"))
    DI_SLA = (("1", "Special SLA"),
              ("2", "Generic SLA"))

    di_type = forms.ChoiceField(label='Disk image type:',
                                widget=forms.Select,
                                choices=DI_TYPE,
                                error_messages={'required': 'Type is Required'})
    di_type.widget.attrs['name'] = 'Disk image type'
    di_type.widget.attrs['class'] = 'ui fluid dropdown'
    di_version = forms.CharField(label='Disk image version:',
                                 error_messages={'required': 'Version is Required'})
    di_fileformat = forms.ChoiceField(label='Disk image format:',
                                      widget=forms.Select,
                                      choices=DI_FORMAT,
                                      error_messages={'required': 'File format is Required'})
    di_fileformat.widget.attrs['name'] = 'Disk image format'
    di_fileformat.widget.attrs['class'] = 'ui fluid dropdown'
    di_description = forms.CharField(label='Descritpion of the image.',
                                     error_messages={'required': 'Description is Required'},
                                     widget=forms.Textarea(attrs={'rows': 10,
                                                                  'cols': 65,
                                                                  'placeholder': 'Here you can describe the content of the image in details. It will be used for search.'}))
    di_picture = forms.FileField(error_messages={'required': 'Picture is Required'})
    di_picture.widget.attrs['style'] = 'display: none;'
    di_encription = forms.BooleanField(label='Do you want your disk image to be encripted?',
                                       required=False,
                                       error_messages={'required': 'Encription is Required'})
    di_SLA = forms.ChoiceField(label='Disk image SLA:',
                               widget=forms.Select,
                               choices=DI_SLA,
                               error_messages={'required': 'SLA is Required'})
    di_SLA.widget.attrs['name'] = 'Disk image SLA'
    di_SLA.widget.attrs['class'] = 'ui fluid dropdown'
    di_price = forms.CharField(label='Price of disk image:',
                               error_messages={'required': 'Price is Required'})
    di_operatingsystem = forms.ChoiceField(label='OS running on the disk image:',
                                           widget=forms.Select,
                                           choices=DI_OS,
                                           error_messages={'required': 'OS is Required'})
    di_operatingsystem.widget.attrs['name'] = 'Disk image OS'
    di_operatingsystem.widget.attrs['class'] = 'ui fluid dropdown'
    di_needsdatafile = forms.BooleanField(label='Does your image need data file?',
                                          required=False,
                                          error_messages={'required': 'Data File is Required'})
    di_obfuscation = forms.BooleanField(label='Is your image obfuscated?',
                                        required=False,
                                        error_messages={'required': 'Obfuscated is Required'})
    di_imagefile = forms.FileField(label='Choose disk image file below:',
                                   error_messages={'required': 'ImageFile is Required'})
    di_imagefile.widget.attrs['style'] = 'display: none;'


class SearchImageForm(forms.Form):
    DI_TYPE = (("VMI", "Virtual machine Image"),
               ("CI", "Container Image"))
    DI_FORMAT = (("ISO", "ISO"),
                 ("DMG", "DMG"),
                 ("FVD", "FVD"),
                 ("IMG", "IMG"),
                 ("NDIF", "NDIF"),
                 ("QCOW", "QCOW"),
                 ("UDIF", "UDIF"),
                 ("VID", "VDI"),
                 ("VHD", "VHD"),
                 ("VMDK", "VMDK"),
                 ("WIM", "WIM"))
    DI_OS = (("10", "Windows"),
             ("20", "Linux"),
             ("30", "Macintosh"))
    DI_SLA = (("1", "Special SLA"),
              ("2", "Generic SLA"))

    di_type = forms.ChoiceField(label='Search by disk image type:',
                                widget=forms.Select,
                                choices=DI_TYPE,
                                error_messages={'required': 'Type is Required'})
    di_type.widget.attrs['class'] = 'ui fluid dropdown'

mini_projekt/use_cases/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.generic import TemplateView, View, FormView
from django.core.urlresolvers import reverse

import requests
import json
import pdb
import time


from .forms import UploadImageForm, SearchImageForm
from .models import Image

# nbar tells the menu on which page we are currently positioned. Please check base_top_menu.html.
#

UPLOAD_IMAGE_URL = "http://194.249.0.47:8080/CcgMiniV01/mini/images/uploadImage"
DELETE_IMAGE_URL = "http://194.249.0.47:8080/CcgMiniV01/mini/images/deleteSpecifiedImages"
GET_IMAGE_URL = "http://194.249.0.47:8080/CcgMiniV01/mini/images/returnSpecifiedImages"
GET_ALL_IMAGES_URL = "http://194.249.0.47:8080/CcgMiniV01/mini/images"


def deleteImage(request):
    if request.method == 'POST':
        if(request.POST.get('image_id')):  # If we get a correct delete POST requeste we proceed with deletion of the local files and form the database.
            data = "[\"{}\"]".format(request.POST['image_id'])
            headers = {'Content-type': 'application/json'}
            r = requests.post(DELETE_IMAGE_URL, data=data, headers=headers)
            Image.objects.filter(image_id=request.POST['image_id']).delete()
            return JsonResponse(r.json(), safe=False)
    else:
        return redirect(reverse('show_image'))


class Home(TemplateView):
    template_name = 'use_cases/index.html'
    nbar = 'home'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['nbar'] = self.nbar
        return context


class Show_image(FormView):
    initial = {}
    nbar = 'show_image'
    template_name = 'use_cases/show_image.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'nbar': self.nbar})

    def post(self, request, *args, **kwargs):
        if(request.POST.get('image_ids')):  # Check if the POST requeste wants us to show all or just specific images and serve appropriately.
            data = json.dumps(request.POST['image_ids'].split())
            headers = {'Content-type': 'application/json', 'Accept': 'application/json'}
            r = requests.post(GET_IMAGE_URL, data=data, headers=headers)
            # pdb.set_trace()
            return JsonResponse(r.json(), safe=False)
        if(request.POST.get('is_all')):
            headers = {'Accept': 'application/json'}
            r = requests.get(GET_ALL_IMAGES_URL, headers=headers)
            return JsonResponse(r.json(), safe=False)


class Search_image(FormView):
    form_class = SearchImageForm
    initial = {}
    nbar = 'search_image'
    template_name = 'use_cases/search_image.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'nbar': self.nbar})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            url = "http://194.249.0.47:8080/CcgMiniV01/mini/images/returnImagesWithGivenType"
            data = "\"{}\"".format(request.POST['di_type'])
            headers = {'Accept': 'application/json', 'Content-type': 'application/json'}
            r = requests.post(url, data=data, headers=headers)
            # pdb.set_trace()
            return JsonResponse(r.json(), safe=False)
        return render(request, self.template_name, {'form': form, 'nbar': self.nbar})


class Upload_image(View):
    form_class = UploadImageForm
    initial = {}
    nbar = 'upload_image'
    template_name = 'use_cases/upload_image.html'

    def uploadImage(self, request):
        uploaded_image = Image(pic=request.FILES['di_picture'],
                               DI=request.FILES['di_imagefile'])
        # JSON string below which will be sent to server as an upload request.
        data = "{{\"description\": \"{0}\", \"title\": \"{1}\", \"iri\": \"../media/uploads/diskimages/{1}\", \"imageType\": \"{2}\", \"fileFormat\": \"{3}\", \"pictureUrl\": \"../media/uploads/images/{4}\", \"encription\": {5}, \"needsData\": {6}, \"obfuscation\": {7}, \"price\": {8}, \"slaId\": {9}, \"operatingSystemId\": {10}, \"ownerId\": 66, \"predecessor\": \"predecessor of image {11}\", \"functionallityId\": 77, \"qualityId\": 88, \"generationTime\": {12} }}"
        data = data.format(request.POST['di_description'],
                           request.FILES['di_imagefile'].name,
                           request.POST['di_type'],
                           request.POST['di_fileformat'],
                           request.FILES['di_picture'].name,
                           "true" if request.POST.get('di_encription') else "false",
                           "true" if request.POST.get('di_needsdatafile') else "false",
                           "true" if request.POST.get('di_obfuscation') else "false",
                           request.POST['di_price'],
                           request.POST['di_SLA'],
                           request.POST['di_operatingsystem'],
                           request.FILES['di_imagefile'].name,
                           int(round(time.time())))
        headers = {'Content-type': 'application/json', 'Accept': 'application/json'}
        r = requests.post(UPLOAD_IMAGE_URL, data=data, headers=headers)
        # TODO: Response check
        uploaded_image.image_id = r.json().get('id')
        uploaded_image.save()
        return r.json()

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form, 'nbar': self.nbar})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            return JsonResponse(self.uploadImage(request), safe=False)
        return render(request, self.template_name, {'form': form, 'nbar': self.nbar})

mini_projekt/use_cases/templates/use_cases/index.html
{% extends "base.html" %}


{% block menu %}
{% endblock menu %}


{% block content %}
  <div id="big-headder" class="ui inverted vertical masthead center aligned segment" style="-ms-flex:1;-webkit-flex:1;flex:1;">

    <div class="ui container floating">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        {# <div class="right item">
          <a class="ui inverted button">Log in</a>
          <a class="ui inverted button">Sign Up</a>
        </div> #}
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header" style="-webkit-text-stroke: 0.04em white; font-weight:bold; color:#D22459">
        Cloud Computing Group
      </h1>
      <h2>Try the use-cases below:</h2>
      <div class="ui three buttons">
        <a class="ui huge primary button" href="{% url 'use_cases:upload_image' %}">Upload Image</a>
        <a class="ui huge primary button" href="{% url 'use_cases:search_image' %}">Search Image</a>
        <a class="ui huge primary button" href="{% url 'use_cases:show_image' %}">Show Image</a>
      </div>

    </div>

  </div>

{% endblock content %}

mini_projekt/use_cases/templates/use_cases/search_image.html
{% extends "base.html" %}
{% load staticfiles %}

{% block menu %}
  {% include "base_top_menu.html" with nbar=nbar visibility="" parameters="pointing inverted"%}
{% endblock menu %}


{% block content %}

   <form class="ui form" action="{% url 'use_cases:search_image' %}" method="post" enctype="multipart/form-data" style="-ms-flex:1;-webkit-flex:1;flex:1;">
    {% csrf_token %}
    <div class="ui vertical stripe segment">
      <div class="ui middle aligned stackable grid container">

        <div class="row">
          <div class="center aligned column" id="header_placeholder">
            <h3 class="ui header" id="header field">Search for your image here</h3>
            <div id="form_errors">
                {% if form.errors %}
                    <div class="ui inverted red segment">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-error">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-error">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div id="results">
            </div>
            <h4 class="ui horizontal divider header">
              <i class="bar chart icon"></i>
              Search
            </h4>
          </div>
        </div>

        <div class="center aligned row">
          <h4 class="ui header"> {{ form.di_type.label }}</h4>
          <div class="field">
            {{ form.di_type }}
          </div>
        </div>

        <div class="row">
          <div class="center aligned column">
            <input class="ui submit huge button" type="submit" value="Submit" />
          </div>
        </div>

        <h4 class="ui horizontal divider header">
          <i class="bar chart icon"></i>
          Results
        </h4>

        <div class="center aligned row">
          <div id="images_container" class="ui doubling stackable four cards"  style="width:inherit;">

          </div>
        </div>

      </div>
    </div>
  </form>
{% endblock content %}
{% block script %}
<script type="text/javascript">

    $(document).ready(function() {
        $('.form').ajaxForm({
            // Handle a successful response.
            success : function(json) {
                // console.log(json); // Log the returned json to the console.
                if(json.length > 0) { // Proceed parsing the response.
                    $('.form').trigger('reset');
                    try {
                        createCard(json); // For each element in returned json we create card, which shows the info about one image container.
                    }
                    catch(err) { // If we couldnt parse the json we got html response including form errors.
                        var elements = $(json);
                        document.getElementById('form_errors').innerHTML = $('#form_errors', elements).html(); // Instead of reloading whole page we just coppy the errors.
                        window.scrollTo(0,0);
                    }
                }
                else { // In case of empty response let the user know what happened.
                    $('#images_container').empty();
                    $('#dividing_header').attr('style', 'width:100%; display: block');
                    $('#images_container').append("<p> No images to show :( </p>");
                }
            },
            // handle a non-successful response
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // Add the error to the dom.
                console.log(xhr.status + ": " + xhr.responseText); // Provide a bit more info about the error to the console.
            }
        });
    });

</script>
{% endblock script %}

mini_projekt/use_cases/templates/use_cases/upload_image.html
{% extends "base.html" %}
{% load staticfiles %}

{% block menu %}
  {% include "base_top_menu.html" with nbar=nbar visibility="" parameters="pointing inverted"%}
{% endblock menu %}


{% block content %}

   <form class="ui form" action="{% url 'use_cases:upload_image' %}" method="post" enctype="multipart/form-data" style="-ms-flex:1;-webkit-flex:1;flex:1;">
    {% csrf_token %}

    <div class="ui vertical stripe segment">
      <div class="ui middle aligned stackable grid container">

        <div class="row">
          <div class="center aligned column" id="header_placeholder">
            <h3 class="ui header" id="header field">Upload your image here!</h3>
            <p id="header text">Please provide as many information about the submitted picture as possible. Doing so you will help the community with providing high quality datasets to explore. Thank you! </p>
            <p id="header id"></p>
            <div id="form_errors">
            {% if form.errors %}
                <div class="ui inverted red segment">
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-error">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-error">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
            </div>
            <div class="ui indicating progress active" style="display:none" id="progress_bar">
              <div class="bar">
                <div class="progress"></div>
              </div>
              <div class="label">Uploading Files</div>
            </div>
            <h4 class="ui horizontal divider header">
              <i class="bar chart icon"></i>
              Specifications
            </h4>
          </div>
        </div>

        <div class="row">
          <div class="six wide column">
            <h4 class="ui header"> {{ form.di_imagefile.label }}</h4>
            <div class="field">
              <div class="ui fluid action input btn-file">
                <input type="text" id="_id_di_imagefile">
                <label for="id_di_imagefile" class="ui icon button">
                   <i class="file outline icon"></i>
                   {{ form.di_imagefile }}
                </label>
              </div>
            </div>
            <h4 class="ui header"> {{ form.di_type.label }}</h4>
            <div class="field">
              {{ form.di_type }}
            </div>
            <h4 class="ui header"> {{ form.di_fileformat.label }}</h4>
            <div class="field">
              {{ form.di_fileformat }}
            </div>
            <h4 class="ui header"> {{ form.di_operatingsystem.label }}</h4>
            <div class="field">
              {{ form.di_operatingsystem }}
            </div>
            <h4 class="ui header"> {{ form.di_SLA.label }}</h4>
            <div class="field">
              {{ form.di_SLA }}
            </div>
            <h4 class="ui header"> {{ form.di_version.label }}</h4>
            <div class="ui fluid icon input">
              {{ form.di_version }}
              <i class="random icon"></i>
            </div>
            <h4 class="ui header"> {{ form.di_price.label }}</h4>
            <div class="ui fluid icon input">
              {{ form.di_price }}
              <i class="euro icon"></i>
            </div><br/><br/>
            <div class="field">
              <div class="ui toggle checkbox">
                {{ form.di_encription }}
                <label>{{ form.di_encription.label }}</label>
              </div>
            </div><br/>
            <div class="field">
              <div class="ui toggle checkbox">
                {{ form.di_needsdatafile }}
                <label>{{ form.di_needsdatafile.label }}</label>
              </div>
            </div><br/>
            <div class="field">
              <div class="ui toggle checkbox">
                {{ form.di_obfuscation }}
                <label>{{ form.di_obfuscation.label }}</label>
              </div>
            </div>
          </div>

          <div class="seven wide right floated column">
            <div class="field">
              <img id= "thumbnail_image" class="ui fluid image" src={% static "use_cases/placeholder.png" %}>
              <div class="ui fluid attached action input btn-file">
                <input type="text" id="_id_di_picture" style="border-top-left-radius: 0px !important;">
                <label for="id_di_picture" class="ui icon button" style="border-top-right-radius: 0px !important;">
                   <i class="file image outline icon"></i>
                   {{ form.di_picture }}
                </label>
              </div>
            </div>
            <div class="field">
              {{ form.di_description }}
            </div>
          </div>

        </div>

        <div class="row">
          <div class="center aligned column">
            <input class="ui submit huge button" type="submit" value="Submit" id="submit_button"/>
          </div>
        </div>

      </div>
    </div>
  </form>

{% endblock content %}
{% block script %}
<script type="text/javascript">

    //Function which copies input image into image container.
    function loadThumbnail(input) {
        if (input[0].files && input[0].files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#thumbnail_image').attr('src', e.target.result);
            };
            reader.readAsDataURL(input[0].files[0]);
        }
    }


    $(document).ready(function() {
        var prev_complete = 0;
        // Initiall set-up of the progress bar.
        $('#progress_bar').progress({
            text: {
                active  : '{percent}% Uploaded',
                success : 'Upload Complete!'
            },
        });

        $('.form').ajaxForm({
            // Prepare progress bar for upload and lock the submit button until the upload is finished.
            beforeSend: function() {
                window.scrollTo(0,0);
                $('#progress_bar').attr('style','display:block');
                prev_complete = 0;
                $('#submit_button').attr('disabled', true);

            },
            // During the upload update the progrss bar.
            uploadProgress: function(event, position, total, percentComplete) {
                if(prev_complete != percentComplete) {
                    $('#progress_bar').progress('increment', percentComplete-prev_complete);
                    prev_complete = percentComplete;
                }
            },
            // Handle a successful response.
            success : function(json) {
                if(json.length) { // We got the html response - form errors.
                    var elements = $(json);
                    document.getElementById('form_errors').innerHTML = $('#form_errors', elements).html(); // Instead of reloading whole page we just coppy the errors.
                    $('#submit_button').attr('disabled', false);
                    $('#progress_bar').attr('style','display:none');
                    window.scrollTo(0,0);
                }
                else { // We got confirmation on successful upload.
                    document.getElementById('header field').innerHTML = "Success!";
                    document.getElementById('header text').innerHTML = "Your image was saved to:    "+ json.location;
                    document.getElementById('header id').innerHTML = "ID:      " +  json.id ;
                    window.scrollTo(0,0);
                    $('.form').trigger('reset');
                    $('#thumbnail_image').attr('src', '{% static "use_cases/placeholder.png" %}');
                    $('#submit_button').attr('disabled', false);
                }
            },
            // Handle a non-successful response.
            error : function(xhr,errmsg,err) {
                $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                    " <a href='#' class='close'>&times;</a></div>"); // Add the error to the dom.
                console.log(xhr.status + ": " + xhr.responseText); // Provide a bit more info about the error to the console.
            }
        });
    });


    // File fields logic.
    var fileExtentionRange = '.jpg .png .iso .dmg .fvd .img .ndif .qcow .udif .vdi .vhd .vmdk .wim .rar'; // Which types of files do we accept. Should be changed or upgraded to automatically fill the appropriate form fields.
    var MAX_SIZE = 5000; // MB
    $(document).on('change', '.btn-file :file', function() {
        var file_btn = $(this); // File field in form.
        var textbox = file_btn.parent().parent().find(':text'); // Text field in form. Our original file field is hidden for design purposes and this is acting instead of it for display.
        // Prepare the request for next function.
        if (navigator.appVersion.indexOf("MSIE") != -1) { // IE
            var label = file_btn.val();
            file_btn.trigger('fileselect', [ 1, label, 0 ]);
        }
        else {
            var label = file_btn.val().replace(/\\/g, '/').replace(/.*\//, '');
            var numFiles = file_btn.get(0).files ? file_btn.get(0).files.length : 1;
            var size = file_btn.get(0).files[0].size;
            file_btn.trigger('fileselect', [ numFiles, label, size, file_btn, textbox ]);
        }
    });

    $('.btn-file :file').on('fileselect', function(event, numFiles, label, size, file_btn, textbox) {
        var postfix = label.substr(label.lastIndexOf('.'));
        if (fileExtentionRange.indexOf(postfix.toLowerCase()) > -1) { // Check the file extension.
            if (size > 1024 * 1024 * MAX_SIZE ) { // Check the file size.
                alert('max size：' + MAX_SIZE + ' MB.');
                    file_btn.removeAttr('name'); // cancel upload file.
            }
            else { // If everything is OK write the file name into our text box.
                textbox.val(label);
                if ( file_btn.is($('#id_di_picture')) ) { // If the uploaded file is the thumbnail picture don't forget to change the thumbnail image.
                    loadThumbnail(file_btn);
                }

            }
        } else {
            alert('Acceptable file types：' + fileExtentionRange);
            file_btn.removeAttr('name'); // cancel upload file.
        }
    });

</script>
{% endblock script %}