mini_projekt/mini_projekt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  url(r'^admin/', include(admin.site.urls)),
  url(r'^', include('use_cases.urls', namespace="use_cases")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_projekt/use_cases/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.Home.as_view(), name="index"),
    url(r'^upload_image/$', views.Upload_image.as_view(), name='upload_image'),
    url(r'^search_image/$', views.Search_image.as_view(), name='search_image'),
    url(r'^show_image/$', views.Show_image.as_view(), name='show_image'),
    url(r'^delete/$', views.deleteImage, name='delete_image'),
]

mini_projekt/templates/base_footer.html
<div class="ui inverted vertical flexrow footer segment">
  <div class="ui container">
    <div class="ui stackable inverted divided equal height stackable grid">
      <div class="three wide column">
        <h4 class="ui inverted header">About</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Demo</a>
        </div>
      </div>
      <div class="three wide column">
        <h4 class="ui inverted header">Services</h4>
        <div class="ui inverted link list">
          <a href="#" class="item">Demo2</a>
        </div>
      </div>
      <div class="seven wide column">
        <h4 class="ui inverted header">Footer Header</h4>
        <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
      </div>
    </div>
  </div>
</div>

mini_projekt/templates/base_top_menu.html
{# depending on the value of the nbar, the correct item in the menu is selected as active #}
<div class="ui large top fixed {{visibility}} {{parameters}} menu">
  {# <a class="toc item">
    <i class="sidebar icon"></i>
   </a> #}
  <div class="ui container">
    <a href="{% url 'use_cases:index' %}" class="{% if nbar == 'home' %}active{% endif %} item">Home</a>
    <a href="{% url 'use_cases:upload_image' %}" class="{% if nbar == 'upload_image' %}active{% endif %} item">Upload Image</a>
    <a href="{% url 'use_cases:search_image' %}" class="{% if nbar == 'search_image' %}active{% endif %} item">Search Image</a>
    <a href="{% url 'use_cases:show_image' %}" class="{% if nbar == 'show_image' %}active{% endif %} item">Show Image</a>
    {# <div class="right menu">
      <div class="item">
        <a href="" class="ui button">Log in</a>
      </div>
      <div class="item">
        <a href="" class="ui primary button">Sign Up</a>
      </div>
    </div> #}
  </div>
</div>